substitutions:
  device_name: air-quality-pms-2
  friendly_name: "Air Quality DWR"
  comment: "Air Quality Sensor (PMS) in Duane Workroom"
  log_level: WARN

packages:
  wifi_ws_conf: github://jduanen/SensorNet/common/wifi_ws.yaml
  dev_conf: github://jduanen/SensorNet/sensors/AirQualityPMS/packages/air-quality-pms-base.yaml
