substitutions:
  device_name: air-quality-pms-0
  friendly_name: "Air Quality MBR"
  comment: "Air Quality Sensor (PMS) in Master Bedroom"
  log_level: WARN

packages:
  wifi_ws_conf: github://jduanen/SensorNet/sensors/common/wifi_ws.yaml
  dev_conf: github://jduanen/SensorNet/sensors/AirQualityPMS/packages/air-quality-pms-base.yaml
