substitutions:
  device_name: air-quality-pms-0
  friendly_name: "Air Quality MBR"
  comment: "Air Quality Sensor (PMS) in Master Bedroom"
  log_level: WARN

packages:
  dev_config: !include packages/air-quality-pms-base.yaml
