substitutions:
  device_name: air-quality-pms-0
  friendly_name: "Air Quality MBR"
  comment: "Air Quality Sensor (PMS) in Master Bedroom"
  log_level: WARN

packages:
  dev_config:
    url: https://github.com/jduanen/SensorNet.git
    files:
      - sensors/common/base.yaml
      - sensors/AirQualityPMS/packages/air-quality-pms-base.yaml
    refresh: 0d  # refresh on rebuild #### TMP TMP TMP
