substitutions:
  device_name: kittycam
  friendly_name: "Kitty Camera"
  comment: "ESP32-S3-Sense Camera with PIR Sensor and White LED"
  log_level: WARN

packages:
  wifi_ws_conf: github://jduanen/SensorNet/sensors/common/wifi_ws.yaml

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

microphone:
  - platform: i2s_audio
    id: kc_mic
    adc_type: external
    i2s_din_pin: GPIO42
    channel: left

i2c:
   - id: camera_i2c
     sda: GPIO40
     scl: GPIO39

i2s_audio:
  i2s_lrclk_pin: GPIO46
  i2s_bclk_pin: GPIO45
  i2s_mclk_pin: GPIO0

esp32_camera:  # XIAO SENSE
  name: Kitty Cam
  id: kitty_cam
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  reset_pin: GPIO9
  max_framerate: 10 fps
  idle_framerate: 0.2 fps
  resolution: 800x600
  jpeg_quality: 10

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "Kittycam PIR Sensor"
    device_class: PRESENCE

output:
  - platform: ledc
    pin: GPIO2    # white LED
    id: kittyCamLED
  - platform: gpio
    pin: GPIO21
    id: led_builtin

light:
  - platform: monochromatic
    output: kittyCamLED
    name: "Kittycam Light"
