substitutions:
  device_name: flamesense
  friendly_name: "Flame Sensor"
  comment: "UVTRON-R2628-based Flame Sensor"
  log_level: WARN
  pulse_threshold: "20"
  no_change_limit: "10"

esphome:
  name: ${device_name}

packages:
  wifi_ws_conf: github://jduanen/SensorNet/common/wifi_ws.yaml

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

globals:
  - id: last_total
    type: int
    restore_value: no
    initial_value: "0"
  - id: no_change_count
    type: int
    restore_value: no
    initial_value: "0"

sensor:
  - platform: pulse_counter
    name: "Flame Detection Pulse Input"
    pin:
      number: GPIO5
      inverted: true
      mode:
        input: true
        pullup: true
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    update_interval: 1s
    total:
      id: pulse_total
      name: "Flame Sense Pulses"

interval:
  - interval: 1s
    then:
      - lambda: |-
          int total = (int) id(pulse_total).state;
          if (total != id(last_total)) {
            id(last_total) = total;
            id(no_change_count) = 0;
          } else if (id(no_change_count) < atoi("${no_change_limit}")) {
            id(no_change_count)++;
          }

          if (total > atoi("${pulse_threshold}") && id(no_change_count) < atoi("${no_change_limit}")) {
            id(led_pwm).turn_on();
          } else {
            id(led_pwm).turn_off();
          }

output:
  - platform: ledc
    id: led_pwm
    pin:
      number: GPIO4
      inverted: true
    frequency: 1000 Hz

light:
  - platform: monochromatic
    name: "GPIO5 LED"
    output: led_pwm
    default_transition_length: 0s
