substitutions:
  device_name: waveshare-audio-1
  friendly_name: "Waveshare Voice FR"
  comment: "Waveshare ESP32-S3 Voice Assistant in Family Room"
  log_level: WARN

packages:
  dev_conf: github://jduanen/SensorNet/voiceAssistants/WaveshareSatellite/packages/waveshare-audio-esp32-s3.yaml
  