substitutions:
  device_name: waveshare-audio-0
  friendly_name: "Waveshare Voice MBR"
  comment: "Waveshare ESP32-S3 Voice Assistant in Master Bedroom"
  log_level: WARN

packages:
  dev_conf: github://jduanen/SensorNet/voiceAssistants/WaveshareSatellite/packages/waveshare-audio-esp32-s3.yaml
