esphome:
  name: airquality-pms-2
  friendly_name: Air Quality Duane's Workroom

esp8266:
  board: esp01_1m

logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air Quality PMS DWR"
    password: !secret wifi_ap_password

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# N.B. must wait >=30s after waking up before reading value
sensor:
  - platform: pmsx003
    type: PMSX003
    update_interval: 0s
    pm_1_0:
      name: "Particulate Matter <1.0µm"
      id: pms1
      accuracy_decimals: 1
      filters:
        - lambda: |-
            if (id(warmedUp).state) {
              return(x);
            } else {
              return {};
            }
    pm_2_5:
      name: "Particulate Matter <2.5µm"
      id: pms2_5
      accuracy_decimals: 1
      filters:
        - lambda: |-
            if (id(warmedUp).state) {
              return(x);
            } else {
              return {};
            }
    pm_10_0:
      name: "Particulate Matter <10.0µm"
      id: pms10
      accuracy_decimals: 1
      filters:
        - lambda: |-
            if (id(warmedUp).state) {
              return(x);
            } else {
              return {};
            }

interval:
  - interval: 2min
    then:
      - wait_until:
          condition:
            api.connected:
      - switch.turn_on: measuring # Will turn itself off later

binary_sensor:
  - platform: template
    name: "Warmed Up"
    id: warmedUp
    filters:
      - delayed_on: 30s
    on_press:
      - delay: 10s
      - switch.turn_off: measuring

switch:
  - platform: gpio
    name: "Measuring"
    id: measuring
    pin:
      number: GPIO5
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - binary_sensor.template.publish:
          id: warmedUp
          state: ON
    on_turn_off:
      - binary_sensor.template.publish:
          id: warmedUp
          state: OFF
  - platform: gpio
    pin:
      number: GPIO5
    id: pmsSet
    restore_mode: ALWAYS_OFF
  - platform: restart
    name: "Restart"
  - platform: gpio
    pin: GPIO4
    name: "Reset"
    inverted: true
