esphome:
  name: airquality-pms-1
  friendly_name: Air Quality Family Room

esp8266:
  board: esp01_1m

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Airquality-Pms-1 Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO5
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm"
    pm_2_5:
      name: "Particulate Matter <2.5µm"
    pm_10_0:
      name: "Particulate Matter <10.0µm"

switch:
  - platform: gpio
    pin: GPIO5
    name: "Sleep"
    id: PMS_Set

  - platform: gpio
    pin: GPIO4
    name: "Reset"
    inverted: true

interval:
  - interval: 120s
    then: 
      - switch.turn_on: PMS_Set
      - delay: 30s
      - switch.turn_off: PMS_Set
