esphome:
  name: birdynomnom
  friendly_name: BirdyNomNom

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BirdyNomNom"
    password: !secret wifi_ap_password

captive_portal:

dallas:
  - pin: GPIO6
    update_interval: 30s

sensor:
  - platform: dallas
    address: 0xd60000098cccdd28
    name: "Loadcell Temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    id: loadcellTemp
  - platform: dallas
    address: 0xe90000000501cf28
    name: "Internal Temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    id: internalTemp
  - platform: hx711
    name: "HX711 Value"
    dout_pin: GPIO4
    clk_pin: GPIO5
    gain: 128
    update_interval: 30s
    id: loadcellValue
    unit_of_measurement: g
    accuracy_decimals: 2
    filters:
      - calibrate_linear:
        - 658467.5238 -> 0.0
        - 1931087.1429 -> 100.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
    name: "Charging"
    id: CHG
    filters:
      - delayed_on: 10s

#  - platform: gpio
#    pin:
#      number: GPIO7
#      mode:
#        input: true
#        pullup: true
#      inverted: true
#    name: "Power Good"
#    id: PGOOD

