esphome:
  name: test8266
  friendly_name: ESP8266 Test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP8266 Test"
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80


sensor:
  - platform: wifi_signal
    name: "ESP8266 Test WiFi Signal"

switch:
  - platform: gpio
    pin: GPIO15  # D8
    name: LED

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO13  # D7
      mode: INPUT_PULLUP
    name: "Button"
  
