substitutions:
  devicename: leddisplay
  upper_devicename: LED_Display

external_components:
  - source:
      type: git
      url: https://github.com/jduanen/ESPHomeComponents
    components: [ led_display ]
    refresh: always

esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename} Fallback Hotspot"
    password: !secret wifi_ap_password

  power_save_mode: none

captive_portal:

web_server:
  port: 80

display:
  - platform: led_display
    id: leds
    brightness: 50
    #auto_clear_enabled: false
    update_interval: never
#    update_interval: 5s
#    lambda: |-
#      if (id(my_button).state) {
#        it.print(0, 0, id(roboto), "A");
#      } else {
#        it.print(0, 0, id(roboto), " ");
#      }
#      it.print("Hello World");

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 6

binary_sensor:
  - platform: gpio
    pin: 0
    name: "Button"
    id: my_button
    # debouncing option
    filters:
      - delayed_on: 20ms

lvgl:
  displays:
    - leds
  widgets:
    - label:
        id: textlabel
        align: CENTER
        text: "Hello World"
