substitutions:
  devicename: leddisplay
  upper_devicename: LED_Display

globals:
  - id: page_index
    type: int
    restore_value: no
    initial_value: '0'

external_components:
  - source:
      type: git
      url: https://github.com/jduanen/ESPHomeComponents
    components: [ led_display ]
    refresh: always

esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}
#  platformio_options:
#    board_build.flash_mode: dio
#    board_build.mcu: esp32c3

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
#  level: VERBOSE
#  level: DEBUG
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename} Fallback Hotspot"
    password: !secret wifi_ap_password

  power_save_mode: none

captive_portal:

web_server:
  port: 80

display:
  - platform: led_display
    id: leds
    intensity: 75
    scroll_enable: true
    scroll_mode: STOP
    scroll_speed: 90ms
    scroll_dwell: 400ms
    scroll_delay: 1500ms
    flip_x: false
    update_interval: 60s
    fonts:
      - MT_Pixel_5x7
      - MatrixLight6
      - MatrixLight6X

#    lambda: |-
#      auto black = Color(0, 0, 0);
#      auto red = Color(255, 0, 0);
#      auto green = Color(0, 255, 0);
#      auto amber = Color(255, 255, 0);
#      it.print(0, 0, id(MT_Pixel_5x7), green, "THIS IS A ");
#      it.print(60, 0, id(MatrixLight6), red, "TEST ");
#      it.print(90, 0, id(MT_Pixel_5x7), amber, "!!!");

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 7
  - file: "fonts/5x7_MT_Pixel.ttf"
    id: MT_Pixel_5x7
    size: 7
  - file: "fonts/MatrixLight6.ttf"
    id: MatrixLight6
    size: 6
  - file: "fonts/MatrixLight6X.ttf"
    id: MatrixLight6X
    size: 6
  - file: "fonts/MatrixLight8.ttf"
    id: MatrixLight8
    size: 8

binary_sensor:
  - platform: gpio
    id: led_display_sensor
    pin: 
      number: 10
      mode:
        input: true
        pulldown: true
    name: "led_display_motion"
    device_class: motion
    on_press:
      then:
        - logger.log: "Motion detected, turning on display"
        - led_display.turn_on
    on_release:
      then:
        - logger.log: "No motion detected, starting off timer"
        - delay: 10s
        - if:
            condition:
              binary_sensor.is_off: led_display_sensor
            then:
              - logger.log: "No motion for 1 min, turning off display"
              - led_display.turn_off
