esphome:
  name: water-temperature
  friendly_name: Water Temperature Garage

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water Temperature"
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80

one_wire:
  - platform: gpio
    pin: GPIO2

sensor:
  - platform: wifi_signal
    name: "Water Temperature WiFi Signal"
    update_interval: 60s
  - platform: dallas_temp
    address: 0xd6000000070eb528
    name: "Water Heater Output Temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    update_interval: 60s
  - platform: dallas_temp
    address: 0x2800000006236d28
    name: "Ambient Temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    update_interval: 60s
