esphome:
  name: "weather-platform"
  friendly_name: Weather Sensors Platform

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
    version: latest
    platform_version: 6.3.2

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather"
    password: !secret wifi_ap_password

captive_portal:

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  frequency: 800kHz

ads1115:
  address: 0x48

sensor:
  - platform: wifi_signal
    name: Weather Platform WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: Weather Platform Uptime
    update_interval: 60s
  - platform: sht3xd
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 60s
  - platform: ads1115
    multiplexer: A0_GND
    gain: 2.048
    name: "ADC Channel 0"
    id: adc_0
    resolution: 16 bits
    filters:
      - offset: 0
      - multiply: 1.0
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6
    update_interval: 10s
  - platform: ads1115
    multiplexer: A1_GND
    gain: 2.048
    name: "ADC Channel 1"
    id: adc_1
    resolution: 16 bits
    filters:
      - offset: 0
      - multiply: 1.0
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6
    update_interval: 10s
  - platform: template
    name: "Wind Direction"
    lambda: |-
      if (adc_0->state && adc_1->state) {
        return (atan2(adc_0->state, adc_1->state) * RAD_TO_DEG);
      } else {
        return {};
      }
    state_class: measurement
    update_interval: 60s
  - platform: dps310
    temperature:
      name: Weather Temperature
      id: weather_temperature
      unit_of_measurement: C
    pressure:
      name: Weather Pressure
      id: weather_pressure
      unit_of_measurement: mmHg
    address: 0x77
    update_interval: 60s

time:
  - platform: homeassistant
    id: esphome_time
    timezone: America/Los_Angeles

#sensor:
#  - platform: pulse_counter
#    pin: 
#      number: GPIO2
#      inverted: false
#      mode:
#        input: true
#        pullup: true
#    name: "Pulse Counter"
#    unit_of_measurement: 'cpm'
#    count_mode:
#      falling_edge: INCREMENT
#      rising_edge: DISABLE
#    update_interval: 10s

## works
#sensor:
#  - platform: sen21231
#    id: person_sensor
#    update_interval: 10s


