substitutions:
  device_name: home-assistant-voice-0
  friendly_name: "Voice Assistant PE DWR"
  comment: "Home Assistant Voice Assistant Preview Edition "
  log_level: WARN

packages:
  dev_conf: github://jduanen/SensorNet/voiceAssistants/HomeAssistantVoicePE/packages/home-assistant-voice.yaml
