substitutions:
  device_name: radiation-0
  friendly_name: "Radiation MBR"
  comment: "Alpha, Beta, and Gamma Radiation Detector in Master Bedroom"
  log_level: WARN

packages:
  hardware: !include packages/radiation-base.yaml
