substitutions:
  device_name: radiation-1
  friendly_name: "Radiation Garage"
  comment: "Alpha, Beta, and Gamma Radiation Detector in Garage"
  log_level: WARN

packages:
  wifi_ws_conf: github://jduanen/SensorNet/sensors/common/wifi.yaml
  dev_conf: github://jduanen/SensorNet/sensors/AirQualityPMS/packages/radiation-base.yaml
