substitutions:
  device_name: radiation-0
  friendly_name: "Radiation MBR"
  comment: "Alpha, Beta, and Gamma Radiation Detector in Master Bedroom"
  log_level: WARN

packages:
  wifi_ws_conf: github://jduanen/SensorNet/sensors/common/wifi.yaml
  dev_conf: github://jduanen/SensorNet/sensors/AirQualityPMS/packages/radiation-base.yaml
