substitutions:
  device_name: water-temperature
  friendly_name: "Water Temperature Garage"
  comment: "Water Temperature Sensors on Hot Water Heater Output and in the Air Nearby"
  log_level: WARN

esp8266:
  board: esp01_1m

packages:
  wifi_ws_conf: github://jduanen/SensorNet/sensors/common/wifi_ws.yaml

one_wire:
  - platform: gpio
    pin: GPIO2

sensor:
  - platform: dallas_temp
    address: 0xd6000000070eb528
    name: "Water Heater Output Temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    update_interval: 60s
  - platform: dallas_temp
    address: 0x2800000006236d28
    name: "Ambient Temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    update_interval: 60s
