esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}

esp8266:
    board: esp01_1m

# Disable logging because the sensor uses the HW serial port
logger:
  level: ${log_level}  # makes uart stream available in esphome logstream
  baud_rate: 0  # disable logging over uart

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_ap_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/jduanen/ESPHomeComponents
    components: [ geigerkit ]
    refresh: always
#  - source:
#      type: local
#      path: /home/jdn/Code/ESPHomeComponents/components/
#    components: [ geigerkit ]

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

geigerkit:
    id: gk0
    cpm:
      name: "counts/min"
    uSv_hr:
      name: "uSieverts/hr"
    volts:
      name: "volts"

sensor:
  - platform: wifi_signal
    id: wifi_rssi
    name: "${friendly_name} Wifi Signal"

switch:
  - platform: gpio
    name: "Reset"
    id: Reset
    pin:
      number: GPIO5  # aka D1
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: Reset
