esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}

esp8266:
  board: esp01_1m  ## esp12e????
  board_flash_mode: dout

logger:
  level: ${log_level}

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "EMS01 Button"
    id: ems01_button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "EMS01 Status"
    id: ems01_status

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_rssi
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: 12
      inverted: true
    cf_pin: 5
    cf1_pin: 14
    current:
      name: "EMS01 Current"
      id: ems01_current
    voltage:
      name: "EMS01 Voltage"
      id: ems01_voltage
    power:
      name: "EMS01 Power"
      id: ems01_power
    energy:
      name: "EMS01 Energy"
      id: ems01_energy
    update_interval: 30s
  - platform: total_daily_energy
    name: "EMS01 Daily Energy"
    power_id: ems01_power

switch:
  - platform: gpio
    name: "EMS01 Relay"
    id: relay
    pin: GPIO4
    on_turn_on:
      - light.turn_on: status_light
    on_turn_off:
      - light.turn_off: status_light

time:
  - platform: sntp
    id: my_time

light:
  - platform: status_led
    pin: GPIO15
    name: "EMS01 Status LED"
    id: status_light
    internal: true
