packages:
  base: !include common/base.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_ap_password
  captive_portal:

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: wifi_signal
    id: wifi_rssi
    name: "${friendly_name} WiFi Signal"
