#!/bin/bash
#
# Script to pull ESPHome config files from gpuServer1.lan
#
# Must install sshpass on HA Server (as Add-on Container)
#  'apk update'
#  'apk add sshpass'
#
#### FIXME replace use of sshpass with SSH keys generated by ssh-keygen

SOURCE="jdn@gpuServer1.lan:Code/SensorNet/sensors"

read -s -p "Enter password: " PASSWD
export SSHPASS="${PASSWD}"
echo ""
echo "Pulling..."

cd /root/config/esphome

# Air Quality Sensors (PMS)
yamlFiles="air-quality-pms-0.yaml air-quality-pms-1.yaml air-quality-pms-2.yaml"
sshpass -e scp ${SOURCE}/AirQualityPMS/${yamlFiles} .
yamlFiles="air-quality-pms-base.yaml"
sshpass -e scp ${SOURCE}/AirQualityPMS/packages/${yamlFiles} .

# Air Quality Sensors (SPS)
yamlFiles="air-quality-sps-0.yaml"
sshpass -e scp ${SOURCE}/AirQualitySPS/${yamlFiles} .

# Environmental Sensors
yamlFiles="env-sensors.yaml"
sshpass -e scp ${SOURCE}/EnvironmentalSensors/${yamlFiles} .

# Feeder Door
yamlFiles="feeder-door.yaml"
sshpass -e scp ${SOURCE}/FeederDoor/${yamlFiles} .

# Home Assistant Voice
yamlFiles="home-assistant-voice-0.yaml"
sshpass -e scp ${SOURCE}/HomeAssistantVoicePE/${yamlFiles} .

# KittyCams
yamlFiles="kittycam.yaml"
sshpass -e scp ${SOURCE}/KittyCam/${yamlFiles} .

yamlFiles="kittycam2.yaml"
sshpass -e scp ${SOURCE}/KittyCamV2/${yamlFiles} .

# LED Sign
yamlFiles="led-sign.yaml"
sshpass -e scp ${SOURCE}/LedDisplay/${yamlFiles} .

# Radiation Sensors
yamlFiles="radiation-0.yaml radiation-1.yaml"
sshpass -e scp ${SOURCE}/Radiation/${yamlFiles} .
yamlFiles="radiation-base.yaml"
sshpass -e scp ${SOURCE}/Radiation/packages/${yamlFiles} .

# Respeaker XVF3800 Satellite
yamlFiles="respeaker-xvf3800-0.yaml"
sshpass -e scp ${SOURCE}/ReSpeakerVXF3800Satellite/${yamlFiles} .
yamlFiles="respeaker-xvf3800.yaml"
sshpass -e scp ${SOURCE}/ReSpeakerVXF3800Satellite/packages/${yamlFiles} .

# Smart Plugs (EMS01)
yamlFiles="smart-plug-ems01-0.yaml"
sshpass -e scp ${SOURCE}/SmartPlugEMS01/${yamlFiles} .
yamlFiles="smart-plug-ems01-base.yaml"
sshpass -e scp ${SOURCE}/SmartPlugEMS01/packages/${yamlFiles} .

# Temperature Sensor with Display
yamlFiles="tempsense0.yaml"
sshpass -e scp ${SOURCE}/TemperatureDisplay/${yamlFiles} .

# Temperature Sensor
yamlFiles="tempsense1.yaml"
sshpass -e scp ${SOURCE}/Temperature/${yamlFiles} .

# Water Heater Temperature Sensor
yamlFiles="water-temperature.yaml"
sshpass -e scp ${SOURCE}/WaterHeater/${yamlFiles} .

# Water Heater Leak Detector
yamlFiles="waterheater-leak-detector.yaml"
sshpass -e scp ${SOURCE}/WaterHeaterLeak/${yamlFiles} .

# Waveshare Satellites
yamlFiles="waveshare-audio-0.yaml waveshare-audio-1.yaml"
sshpass -e scp ${SOURCE}/WaveshareSatellite/${yamlFiles} .
yamlFiles="waveshare-audio-esp32-s3.yaml"
sshpass -e scp ${SOURCE}/WaveshareSatellite/packages/${yamlFiles} .

# Finish up
#### TODO print any failures (after making this detect failures and go on)

unset SSHPASS
echo "Done copying"
