#!/bin/bash
#
# Script to pull ESPHome config files from gpuServer1.lan to HA Server
#
# Must install sshpass on HA Server (as Add-on Container)
#  'apk update'
#  'apk add sshpass'
#
#### FIXME replace use of sshpass with SSH keys generated by ssh-keygen
#### TODO consider doing this with rsync instead

SOURCE="jdn@gpuServer1.lan:Code/SensorNet"
CONTROLLERS="${SOURCE}/controllers"
SENSORS="${SOURCE}/sensors"
VOICE_ASSISTANTS="${SOURCE}/voiceAssistants"

read -s -p "Enter password: " PASSWD
export SSHPASS="${PASSWD}"
echo ""
echo "Pulling..."

cd /root/config/esphome


# **Controllers
# Feeder Door
yamlFiles="feeder-door.yaml"
sshpass -e scp ${CONTROLLERS}/FeederDoor/${yamlFiles} .


# **Sensors
# Air Quality Sensors (PMS)
yamlFiles="air-quality-pms-0.yaml air-quality-pms-1.yaml air-quality-pms-2.yaml"
for f in ${yamlFiles}; do
  sshpass -e scp ${SENSORS}/AirQualityPMS/${f} .
done

# Air Quality Sensors (SPS)
yamlFiles="air-quality-sps-0.yaml"
sshpass -e scp ${SENSORS}/AirQualitySPS/${yamlFiles} .

# Environmental Sensors
yamlFiles="env-sensors.yaml"
sshpass -e scp ${SENSORS}/EnvironmentalSensors/${yamlFiles} .

# KittyCams
yamlFiles="kittycam.yaml"
sshpass -e scp ${SENSORS}/KittyCam/${yamlFiles} .

yamlFiles="kittycam2.yaml"
sshpass -e scp ${SENSORS}/KittyCamV2/${yamlFiles} .

# LED Sign
yamlFiles="led-sign.yaml"
sshpass -e scp ${SENSORS}/LedSign/${yamlFiles} .

# Radiation Sensors
yamlFiles="radiation-0.yaml radiation-1.yaml"
for f in ${yamlFiles}; do
    sshpass -e scp ${SENSORS}/Radiation/${f} .
done

# Smart Plugs (EMS01)
yamlFiles="smart-plug-ems01-0.yaml"
sshpass -e scp ${SENSORS}/SmartPlugEMS01/${yamlFiles} .

# Temperature Sensor with Display
yamlFiles="tempsense0.yaml"
sshpass -e scp ${SENSORS}/TemperatureDisplay/${yamlFiles} .

# Temperature Sensor
yamlFiles="tempsense1.yaml"
sshpass -e scp ${SENSORS}/Temperature/${yamlFiles} .

# Water Heater Temperature Sensor
yamlFiles="water-temperature.yaml"
sshpass -e scp ${SENSORS}/WaterHeater/${yamlFiles} .

# Water Heater Leak Detector
yamlFiles="waterheater-leak-detector.yaml"
sshpass -e scp ${SENSORS}/WaterHeaterLeak/${yamlFiles} .


# **Voice Assistants
# Home Assistant Voice
yamlFiles="home-assistant-voice-0.yaml"
sshpass -e scp ${VOICE_ASSISTANTS}/HomeAssistantVoicePE/${yamlFiles} .

# Respeaker XVF3800 Satellite
yamlFiles="respeaker-xvf3800-0.yaml"
sshpass -e scp ${VOICE_ASSISTANTS}/ReSpeakerVXF3800Satellite/${yamlFiles} .

# FutureProofHomes Satellite1
yamlFiles="satellite1-cfec40.yaml"
sshpass -e scp ${VOICE_ASSISTANTS}/Satellite1/${yamlFiles} .

# Waveshare Satellites
yamlFiles="waveshare-audio-0.yaml waveshare-audio-1.yaml"
for f in ${yamlFiles}; do
    sshpass -e scp ${VOICE_ASSISTANTS}/WaveshareSatellite/${f} .
done


# **Secrets file
sshpass -e scp ${SOURCE}/common/secrets.yaml .

# Finish up
#### TODO print any failures (after making this detect failures and go on)

unset SSHPASS
echo "Done copying"
