#!/bin/bash
#
# Script to push ESPHome config files from HA Server to gpuServer1.lan
#
# Must install sshpass on HA Server (as Add-on Container)
#  'apk update'
#  'apk add sshpass'
#
#### FIXME replace use of sshpass with SSH keys generated by ssh-keygen
#### TODO consider doing this with rsync

TARGET="jdn@gpuServer1.lan:Code/SensorNet/config/esphome/"

read -s -p "Enter password: " PASSWD
export SSHPASS="${PASSWD}"
echo ""
echo "Pushing..."

cd /root/config/esphome


# **Controllers
# Feeder Door
yamlFiles="feeder-door.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

#### FIXME DRY this up or change method

# **Sensors
# Air Quality Sensors (PMS)
yamlFiles="air-quality-pms-0.yaml air-quality-pms-1.yaml air-quality-pms-2.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Air Quality Sensors (SPS)
yamlFiles="air-quality-sps-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Environmental Sensors
yamlFiles="env-sensors.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# KittyCams
yamlFiles="kittycam.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

yamlFiles="kittycam2.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# LED Sign
yamlFiles="led-sign.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Radiation Sensors
yamlFiles="radiation-0.yaml radiation-1.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Smart Plugs (EMS01)
yamlFiles="smart-plug-ems01-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Temperature Sensor with Display
yamlFiles="tempsense0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Temperature Sensor
yamlFiles="tempsense1.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Water Heater Temperature Sensor
yamlFiles="water-temperature.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Water Heater Leak Detector
yamlFiles="waterheater-leak-detector.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}


# **Voice Assistants
# Home Assistant Voice
yamlFiles="home-assistant-voice-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Respeaker XVF3800 Satellite
yamlFiles="respeaker-xvf3800-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# FutureProofHomes Satellite1
yamlFiles="satellite1-cfec40.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}

# Waveshare Satellites
yamlFiles="waveshare-audio-0.yaml waveshare-audio-1.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}


# Finish up
#### TODO print any failures (after making this detect failures and go on)

unset SSHPASS
echo "Done copying"
