#!/bin/bash
#
# Script to push ESPHome config files to gpuServer1.lan
#
# Must install sshpass on HA Server (as Add-on Container)
#  'apk update'
#  'apk add sshpass'
#
#### FIXME replace use of sshpass with SSH keys generated by ssh-keygen

TARGET="jdn@gpuServer1.lan:Code/SensorNet/sensors"

read -s -p "Enter password: " PASSWD
export SSHPASS="${PASSWD}"
echo ""
echo "Copying..."

cd /root/config/esphome

# Air Quality Sensors (PMS)
yamlFiles="air-quality-pms-0.yaml air-quality-pms-1.yaml air-quality-pms-2.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/AirQualityPMS/
yamlFiles="air-quality-pms-base.yaml"
sshpass -e scp packages/${yamlFiles} ${TARGET}/AirQualityPMS/packages/

# Air Quality Sensors (SPS)
yamlFiles="air-quality-sps-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/AirQualitySPS/

# Environmental Sensors
yamlFiles="env-sensors.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/EnvironmentalSensors/

# Feeder Door
yamlFiles="feeder-door.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/FeederDoor/

# Home Assistant Voice
yamlFiles="home-assistant-voice-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/HomeAssistantVoicePE/

# KittyCams
yamlFiles="kittycam.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/KittyCam/

yamlFiles="kittycam2.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/KittyCamV2/

# LED Sign
yamlFiles="led-sign.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/LedDisplay/

# Radiation Sensors
yamlFiles="radiation-0.yaml radiation-1.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/Radiation/
yamlFiles="radiation-base.yaml"
sshpass -e scp packages/${yamlFiles} ${TARGET}/Radiation/packages/

# Respeaker XVF3800 Satellite
yamlFiles="respeaker-xvf3800-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/ReSpeakerVXF3800Satellite/
yamlFiles="respeaker-xvf3800.yaml"
sshpass -e scp packages/${yamlFiles} ${TARGET}/ReSpeakerVXF3800Satellite/packages/

# Smart Plugs (EMS01)
yamlFiles="smart-plug-ems01-0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/SmartPlugEMS01/
yamlFiles="smart-plug-ems01-base.yaml"
sshpass -e scp packages/${yamlFiles} ${TARGET}/SmartPlugEMS01/packages/

# Temperature Sensor with Display
yamlFiles="tempsense0.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/TemperatureDisplay/

# Temperature Sensor
yamlFiles="tempsense1.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/Temperature/

# Water Heater Temperature Sensor
yamlFiles="water-temperature.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/WaterHeater/

# Water Heater Leak Detector
yamlFiles="waterheater-leak-detector.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/WaterHeaterLeak/

# Waveshare Satellites
yamlFiles="waveshare-audio-0.yaml waveshare-audio-1.yaml"
sshpass -e scp ${yamlFiles} ${TARGET}/WaveshareSatellite/
yamlFiles="waveshare-audio-esp32-s3.yaml"
sshpass -e scp packages/${yamlFiles} ${TARGET}/WaveshareSatellite/packages/

# Finish up
#### TODO print any failures (after making this detect failures and go on)

unset SSHPASS
echo "Done copying"
