substitutions:
  device_name: feeder-door
  friendly_name: "Feeder Door Controller"
  comment: "Cat Feeding Machine Door Open/Close Controller"
  max_number_of_steps: 2440.0  # hand-tuned
  max_transit_time: "8s"       # hand-tuned
  max_speed: "400 steps/s"     # hand-tuned  #### TODO set to 250????

esphome:
#  on_boot:
#    priority: 600  # after HW, but before WiFi
#    then:
#      - script.execute: home_door_backward

packages:
  wifi_ws_conf: github://jduanen/SensorNet/sensors/common/wifi_ws.yaml

esp8266:
  board: esp01_1m

sensor:
  - platform: template
    name: "Position Sensor"
    id: position

stepper:
  - platform: uln2003
    id: door_stepper
    pin_d: GPIO15  # D8
    pin_c: GPIO13  # D7
    pin_b: GPIO12  # D6
    pin_a: GPIO14  # D5
    sleep_when_done: true
    max_speed: ${max_speed}
    acceleration: inf
    deceleration: inf

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO4  # D2
      mode: INPUT_PULLUP
    name: "Door Open Switch"
    id: door_open_switch
    filters:
      - invert:
  - platform: gpio
    pin: 
      number: GPIO5  # D1
      mode: INPUT_PULLUP
    name: "Door Close Switch"
    id: door_close_switch
    filters:
      - invert:

switch:
  - platform: template
    name: "Home Feeder Door"
    id: home_script_switch
    optimistic: false
    turn_on_action:
      - script.execute: home_door_backward
      - switch.turn_off: home_script_switch


script:
  - id: home_door_backward
    then:
      - logger.log: "Start homing"
      - while:
          condition:
            binary_sensor.is_off: door_close_switch
          then:
            - stepper.set_target:
                id: door_stepper
                target: !lambda 'return id(door_stepper).current_position - 10;'
            - delay: 100ms
      - logger.log:
          format: "Homed: %d"
          args: [ 'id(door_stepper).current_position' ]
      - stepper.set_target:
          id: door_stepper
          target: !lambda 'return id(door_stepper).current_position;'
      - stepper.report_position:
          id: door_stepper
          position: 0
      - logger.log:
          format: "End Homing: %d"
          args: [ 'id(door_stepper).current_position' ]

cover:
  - platform: template
    name: "Feeder Door"
    id: feeder_door
    has_position: false
    lambda: |-
      if (id(door_close_switch).state) return 0.0f;  // COVER_CLOSED
      if (id(door_open_switch).state) return 1.0f;   // COVER_OPEN
      return 0.5f;  // COVER_CLOSING
    open_action:
      - stepper.set_target:
          id: door_stepper
          target: !lambda 'return ${max_number_of_steps};'
      - wait_until:
          condition:
            binary_sensor.is_on: door_open_switch
          timeout: ${max_transit_time}
      - logger.log:
          format: "Feeder door open: %d"
          args: [ 'id(door_stepper).current_position' ]
    close_action:
      - stepper.set_target:
          id: door_stepper
          target: 0.0
      - wait_until:
          condition:
            binary_sensor.is_on: door_close_switch
          timeout: ${max_transit_time}
      - logger.log:
          format: "Feeder door closed: %d"
          args: [ 'id(door_stepper).current_position' ]
    stop_action:
      - stepper.set_target:
          id: door_stepper
          target: !lambda 'return id(door_stepper).current_position;'
      - logger.log:
          format: "Feeder door stopped: %d"
          args: [ 'id(door_stepper).current_position' ]
    on_open:
      - logger.log: "Feeder door is open"
    on_closed:
      - logger.log: "Feeder door is closed"
